defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

tok_data:
  train_file: "data/train.json"
  val_file: "data/test.json"
  tokenizer_path: "tokenizer/tokenizer.json"

data:
  datapath: data
  train_file: "train.json"
  val_file: "test.json"
  test_file: "test.json"
  num_workers: 32
  split_str: "Command:"
  
model:
  name: "Pythia-${model.n_layer}-${model.n_head}-${model.n_embd}-transformer_search"
  batch_size: 2048
  accumulate_grad_batches: 1
  block_size: 128
  epochs: 100
  n_layer: 24
  n_head: 8
  n_embd: 256
  vocab_size: 26
  padded_vocab_size: 26
  bos_id: 21
  eos_id: 25

optim:
  lr: 1e-2

eval:
  num_examples: 2048
  batch_size: 2048
  results_dir: "data/eval_results/${model.name}"

convert_hf:
  in_path: "temp/${model.name}"
  out_path: "temp/hf_${model.name}"

inference:
  modelpath: "./temp/hf_Pythia-12-8-256-transformer_search"
  datapath: ${data.datapath}/test_set/
  batch_size: 2048